### ISSUE TITLE
Add channel support 

### ISSUE THREAD

**Issue by tuxmaster** [majn/telegram-purple#122]
New to the telegram API.
https://telegram.org/blog/channels

**Comment by 1kko** [comment]
+1 for this!

**Comment by nmpx** [comment]
+1

**Comment by majn** [comment]
A few considerations for implementing channels in tgp. This is just a brain-dump for other contributors (and myself):

- Delivering historic Messages is different in channels and regular chats
  * Unread historic messages are not necessarily pushed to all clients, the client must keep track of that manually
  * Messages may be received twice, the client must keep track of known messages to avoid printing them twice.
  * There is an internal message ID (server_id) that indicates the sequence number of each message in a channel. The first message has the server_id=0. This id is globally permanent and will not change when a new session is created.

- Contrary to chats users seem to be always able to fetch the full message history of all channels and supergroups.

- When channels are LEFT they won't show up in the dialogue list anymore. This is contrary to regular chats, that just remain a zombies with a flag TGLCHF_LEFT or no flag at all and 0 active users (in some cases). 

# Problems:
- Libpurple message history is immutable and cannot be changed after printing a message. tgp currently keeps an internal first-in first-out queue of all messages to ensure that the messages are being printed in the correct order, even when its necessary to fetch additional info (like attached pictures) before this can be done. For non-channels libtgl ensures that tgp receives the messages in the correct order, but in channels there may be holes that need to be filled before the message log can be printed. This means that the queue may not be processed till all historic messages have been fetched and the messages have been inserted into the correct position of the queue 

- libtgl **tgl_do_get_history** expects an offset and a limit for fetching historical messages. When a message is being received in a channel it may be the first of an unknown amount of remaining messages. This makes it impossible to determine the newest sequence number and calculate the necessary offset for fetching missing history.

- **tgl_do_get_history** will not fetch more than N messages at once (100?), which means multiple calls to **tgl_do_get_history** may be necessary to fetch all the missing messages.

- The history in supergroups is potentially really big and should be capped in some way. There are supergroups with backlogs of 16k messages, libpurple clients will not handle printing this amount of messages well.

## Client-specific issues

- Adium won't store PurpleChats permanently in the blist, which means that storing the server_id in the chat will not work for it.

# Tasks

- [ ] Support writing and sending messages in channels and supergroups by implementing them as a new special case of group chats.
- [ ] Support fetching full channel history without any holes
   * [ ] Keep track of the last received message ID in each channel to figure out when holes in the history exist
   * [ ] Find a way to figure out the newest message server_id for channels to allow fetching historic messages. Eventually draft a pull request for libtgl test branch to include the necessary changes for this.
   * [ ] Identify historic channel messages when receiving and make sure to insert them into the correct position in **new_messages**

The following issues are lower priority and probably an extra ticket:

- [ ] Support creating and leaving channels
- [ ] Offer functions for administrating channel settings

**Comment by BenWiederhake** [comment]
Closing this, as 1.3.0 should support supergroups and channels.  If there are any issues, please open a new issue.
